CREATE TABLE main2 (
    name TEXT DEFAULT '',
    wincount NUMERIC DEFAULT 0,
    playerid NUMERIC DEFAULT 1,
    groupid NUMERIC DEFAULT 1,
    PRIMARY KEY(playerid, groupid)
);

ALTER TABLE main2 ALTER COLUMN name SET NOT NULL;
ALTER TABLE main2 ALTER COLUMN wincount SET NOT NULL;
ALTER TABLE main2 ALTER COLUMN playerid SET NOT NULL;
ALTER TABLE main2 ALTER COLUMN groupid SET NOT NULL;